apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: puqme-staging

resources:
  - ../../base

images:
  - name: ghcr.io/puqme/api
    newTag: staging
  - name: ghcr.io/puqme/web
    newTag: staging
  - name: ghcr.io/puqme/websocket
    newTag: staging
  - name: ghcr.io/puqme/admin
    newTag: staging

patches:
  - target:
      kind: Namespace
      name: puqme
    patch: |-
      - op: replace
        path: /metadata/name
        value: puqme-staging
